<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * Please visit Magefan.com for license details (https://magefan.com/end-user-license-agreement).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/** @var $block \Magefan\Blog\Block\Social\AddThis */
?>
<script type="text/javascript">
    var addthis_config = {
        "ui_language": '<?php echo $block->getAddThisLanguage() ?>',
        "data_track_clickback":false
    }
</script>
<script type="text/javascript" async src="<?php echo '/' . '/' ?>s7.addthis.com/js/250/addthis_widget.js#pubid=<?php echo $block->getAddThisPubId() ?>"></script>
