<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * Please visit Magefan.com for license details (https://magefan.com/end-user-license-agreement).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/** @var $block \Magefan\Blog\Block\Social\AddThis */
?>
<script type="text/javascript">
    var addthis_config = {
        "ui_language": '<?= $block->escapeHtml($block->getAddThisLanguage()) ?>',
        "data_track_clickback":false
    }
</script>
<script type="text/javascript" async
        src="<?= '/' . '/' ?>s7.addthis.com/js/300/addthis_widget.js#pubid=<?= $block->escapeUrl($block->getAddThisPubId()) ?>"></script>
