<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * Please visit Magefan.com for license details (https://magefan.com/end-user-license-agreement).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * @var $block \Magento\Framework\View\Element\Template
 * @var $mfSecureRenderer \Magefan\Community\Api\SecureHtmlRendererInterface
 * @var $mfHyvaThemeDetection \Magefan\Community\Api\HyvaThemeDetectionInterface
 */
?>
<?php
$helper = $this->helper(\Magefan\Blog\Helper\Data::class);
?>

<?php if (!$helper->isOriginMfLazyLoadEnable()) { ?>
    <?php if (!$mfHyvaThemeDetection->execute()) { ?>
        <?php $script = "
            require(['jquery', 'domReady!'], function($){
                if ($('.mfblogunveil').length) {
                    require(['Magefan_Blog/js/lib/mfblogunveil'], function(){
                        $('.mfblogunveil').mfblogunveil();
                    });
                }
            });
        "; ?>
    <?php } else { ?>
        <?php $script = "
            /* e.g. hyva theme */
            document.addEventListener('DOMContentLoaded', function(){
                var items =  document.getElementsByClassName('mfblogunveil');
                var el, url;
                if (items.length) {
                    for (var i=0; i<items.length;i++) {
                        el = items[i];
                        url = el.getAttribute('data-original');
                        if (!url) {
                            continue;
                        };
                        if ('IMG' == el.tagName) {
                            el.src = url;
                        } else {
                            el.style.backgroundImage = \"url('\" + url  + \"')\";
                        }
                    }
                }
            });
        "; ?>
    <?php } ?>
    <?= /* @noEscape */ $mfSecureRenderer->renderTag('script', [], $script, false) ?>
<?php } ?>
