<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * Please visit Magefan.com for license details (https://magefan.com/end-user-license-agreement).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog category info template
 *
 * @var $block \Magefan\Blog\Block\Category\Info
 */
?>

<?php if ($content = $block->getContent()): ?>
    <div class="category-content"><?= /*@noEscape*/ $content ?></div>
<?php endif ?>
