<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * Please visit Magefan.com for license details (https://magefan.com/end-user-license-agreement).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog post comments template
 *
 * @var $block \Magefan\Blog\Block\Post\View\Comments
 */
?>
<div id="disqus_thread"></div>
<script>
    var disqus_config = function () {
        this.page.url = "<?= $block->escapeUrl($block->getPost()->getPostUrl()) ?>";
        <?php /*this.page.identifier = "<?= $block->escapeHtml($block->getPost()->getUrl()) ?>" */ ?>
    };

    (function() {
        var d = document, s = d.createElement('script');
        s.src = '<?= $block->escapeHtml('/' . '/' .  $block->getDisqusShortname()) ?>.disqus.com/embed.js';
        s.setAttribute('data-timestamp', +new Date());
        (d.head || d.body).appendChild(s);
    })();
</script>
