<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * Please visit Magefan.com for license details (https://magefan.com/end-user-license-agreement).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog post comments template
 *
 * @var $block \Magefan\Blog\Block\Post\View\Comments
 * @var $mfSecureRenderer \Magefan\Community\Api\SecureHtmlRendererInterface
 */
?>

<div id="fb-root"></div>
<?php $script = "(function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = '" . $block->escapeJs($block->getFbSdkJsUrl()) . "';
    fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));
"; ?>
<?= /* @noEscape */ $mfSecureRenderer->renderTag('script', [], $script, false) ?>
<div class="post-comments clear">
    <div class="fb-comments"
         data-href="<?= $block->escapeUrl($block->getPost()->getPostUrl()) ?>"
         data-width="100%"
         data-numposts="<?= $block->escapeHtml($block->getNumberOfComments()) ?>">
    </div>
</div>
