<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * Please visit Magefan.com for license details (https://magefan.com/end-user-license-agreement).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
     $id = 'blog_comment_privacy_' . $block->getCommentType();
?>
<div class="input-box required" novalidate="novalidate">
    <input type="checkbox"
           value="1"
           data-validate="{required:true}"
           class="checkbox required-entry"
           id="<?= $block->escapeHtml($id) ?>"
           name="privacy">
    <?php
    $privacyPolicy =
        "<a href=" .
            $block->escapeHtml($block->getUrl('privacy-policy-cookie-restriction-mode')) .
            " target='_blank' style='text-decoration: underline;'>". __('privacy policy') .
        "</a>";
    ?>
    <label for="<?= $block->escapeHtml($id) ?>"
           class="required">
        <?= /*@noEscape*/ __('Yes, I have read the %1 and agree to the processing of my personal data.', $privacyPolicy) ?>
    </label>
</div>


