<?php
/**
 * Copyright © 2015 Ihor Vansach (ihor@magefan.com). All rights reserved.
 * See LICENSE.txt for license details (http://opensource.org/licenses/osl-3.0.php).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog post list item template
 *
 * @var $block \Magefan\Blog\Block\Post\AbstractPost
 */
?>
<?php
    $_post = $this->getPost();
    $_postUrl = $block->escapeUrl($_post->getPostUrl());
    $_postName = $block->escapeHtml($_post->getTitle(), null, true);

    $imageHelper = $this->helper('Magefan\Blog\Helper\Image');
    $imageWidth = 500;
    $imageHeight = 200;
?>
<li class="post-holder post-holder-<?= $_post->getId() ?>">
    <div class="post-header">

        <div class="post-title-holder clearfix">
            <h2 class="post-title">
                <a class="post-item-link"
                   href="<?= $_postUrl ?>">
                    <?= $_postName; ?>
                </a>
            </h2>
        </div>

        <?= $this->getInfoHtml() ?>
    </div>

    <div class="post-content">
        <div class="post-description clearfix">
            <?php if ($featuredImage = $_post->getFeaturedImage()) { ?>
            <div class="post-ftimg-hld">
                <a href="<?= $_postUrl ?>" title="<?= $_postName ?>">
                    <amp-img layout="responsive" width="<?= $imageWidth ?>" height="<?= $imageHeight ?>" src="<?= $this->helper('Magefan\Blog\Helper\Image')->init($_post->getFeaturedImg())->resize($imageWidth, $imageHeight) ?>" alt="<?= $_postName ?>"></amp-img>
                </a>
            </div>
            <?php } ?>
            <div class="post-text-hld clearfix">
                <?= $block->getShorContent() ?>
            </div>
            <a class="post-read-more" href="<?= $_postUrl ?>" title="<?= $_postName ?>"
               >
               <?= __('Read more &#187;') ?>
            </a>
        </div>
    </div>
    <div class="post-footer">

    </div>
</li>