<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * See LICENSE.txt for license details (http://opensource.org/licenses/osl-3.0.php).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog sidebar custom HTML template
 *
 * @var $block \Magefan\Blog\Block\Sidebar\Search
 */
?>
<?php $conetnt = $block->getContent() ?>
<?php if ($conetnt) { ?>
    <div class="widget block blog-custom" >
        <?php /* without html encode */ ?>
        <?= $conetnt ?>
    </div>
<?php } ?>