<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * Please visit Magefan.com for license details (https://magefan.com/end-user-license-agreement).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog sidebar popular posts template
 *
 * @var $block \Magefan\Blog\Block\Sidebar\Popular
 */
?>

<?php
$_postCollection = $block->getPostCollection();
?>
<?php if ($_postCollection->count()) { ?>
    <div class="widget block block-popular-posts" data-bind="scope: 'popular-posts'">
        <div class="block-title">
            <strong><?= $block->escapeHtml(__('Popular Posts')) ?></strong>
        </div>
        <div class="block-content">
            <?php foreach ($_postCollection as $_post) { ?>
                <div class="item">
                    <a class="post-item-link"
                       href="<?= $block->escapeUrl($_post->getPostUrl()) ?>">
                        <?= $block->escapeHtml($_post->getTitle()) ?>
                    </a>
                </div>
            <?php } ?>
        </div>
    </div>
<?php } ?>