<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * Please visit Magefan.com for license details (https://magefan.com/end-user-license-agreement).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog sidebar related posts template
 *
 * @var $block \Magefan\Blog\Block\Post\View\RelatedProducts
 */
?>

<?php
$items = $block->getItems();
$image = 'product_thumbnail_image';
?>

<?php if (count($items)) { ?>
<div class="widget block block-<?= $block->escapeHtml(str_replace('_', '-', $block->getWidgetKey())) ?> block-list-posts" >
    <div class="block-title">
        <strong><?= $block->escapeHtml(__($block->getBlockTitle() ?: 'Related Products')) ?></strong>
    </div>

    <ol class="product-items">
        <?php foreach ($items as $_item) { ?>
        <li class="product-item">
            <div class="product-item-info" >
                <a class="product-item-photo" href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>" title="<?= $block->escapeHtml($_item->getName()) ?>">
                    <?= $block->getImage($_item, $image)->toHtml(); ?>
                </a>
                <div class="product-item-details">
                    <strong class="product-item-name">
                        <a class="product-item-link" href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>"  title="<?= $block->escapeHtml($_item->getName()) ?>">
                            <span><?= $block->escapeHtml($_item->getName()) ?></span>
                        </a>
                    </strong>
                    <?= /*@noEscape*/ $block->getProductPrice($_item); ?>
                    <div class="product-item-actions">
                        <div class="actions-primary">

                        </div>
                    </div>
                </div>
            </div>
        </li>
        <?php } ?>
    </ol>
</div>
<?php } ?>
