<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * Please visit Magefan.com for license details (https://magefan.com/end-user-license-agreement).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog sidebar posts list template
 *
 * @var $block \Magefan\Blog\Block\Post\PostList\AbstractList
 */
?>

<?php
    $_postCollection = $block->getPostCollection();
?>
<?php
    $width = $block->getBlockImageWidth() ?: 300;
    $height = $block->getBlockImageheight() ?: 200;
    $imageHelper = $this->helper(\Magefan\Blog\Helper\Image::class);
?>
<?php if ($_postCollection->count()) { ?>
<?php /*
<div class="widget block block-<?= $block->escapeHtml(str_replace('_', '-', $block->getWidgetKey())) ?> block-list-posts">
    <div class="block-title">
        <strong><?= $block->escapeHtml(__($block->getBlogTitle() ?: 'Recent Posts')) ?></strong>
    </div>
    <div class="block-content">
        <?php foreach ($_postCollection as $_post) { ?>
            <?php
                $_postUrl = $block->escapeUrl($_post->getPostUrl());
                $_postName = $block->escapeHtml($_post->getTitle());
            ?>
            <div class="item">
                <?php $featuredImage = $_post->getFeaturedListImage() ?: $_post->getFeaturedImage(); ?>
                <?php if ($featuredImage) { ?>
                    <div class="post-image">
                        <?php
                        $featuredImgAlt = $_post->getData('featured_list_img_alt') ?: $_post->getData('featured_img_alt');
                        if (!$featuredImgAlt) {
                            $featuredImgAlt =  $_postName;
                        }
                        ?>
                        <a class="post-item-link" title="<?= $_postName ?>" href="<?= $_postUrl ?>">
                            <img src="<?= $imageHelper->init($_post->getFeaturedListImg() ?: $_post->getFeaturedImg())->resize($width, $height); ?>"
                                 alt="<?= $block->escapeHtml($featuredImgAlt) ?>" />
                        </a>
                    </div>
                <?php } ?>

                <div class="post-item-link-date">
                    <a class="post-item-link" title="<?= $_postName ?>" href="<?= $_postUrl ?>">
                        <?= $_postName ?>
                    </a>

                    <?php if ($featuredImage && $_post->isPublishDateEnabled()) { ?>
                        <div class="post-item-date">
                            <span class="value"><?= $block->escapeHtml($_post->getPublishDate()) ?></span>
                        </div>
                    <?php } ?>
                </div>

            </div>
        <?php } ?>
    </div>
</div>
*/ ?>

<div class="widget block block-<?= $block->escapeHtml(str_replace('_', '-', $block->getWidgetKey())) ?> block-list-posts">
    <div class="block-title-wrap">
        <div class="block-title">
            <strong><?= $block->escapeHtml(__($block->getBlogTitle() ?: 'Recent Posts')) ?></strong>
        </div>
    </div>
    <div class="block-content">
        <!-- post list -->
        <div class="post-list">
        <?php foreach ($_postCollection as $_post) { ?>
            <?php
            $_postUrl = $block->escapeUrl($_post->getPostUrl());
            $_postName = $block->escapeHtml($_post->getTitle());
            ?>
            <!-- post item -->
            <div class="post-item d-flex mb-4">
                <?php $featuredImage = $_post->getFeaturedListImage() ?: $_post->getFeaturedImage(); ?>
                <?php if ($featuredImage) { ?>
                <div class="image-container">
                    <?php
                    $featuredImgAlt = $_post->getData('featured_list_img_alt') ?: $_post->getData('featured_img_alt');
                    if (!$featuredImgAlt) {
                        $featuredImgAlt =  $_postName;
                    }
                    ?>
                    <a class="image-wrap _4x3" title="<?= $_postName ?>" href="<?= $_postUrl ?>">
                        <?php $featuredImage = $_post->getFeaturedListImage() ?: $_post->getFeaturedImage(); ?>
                        <?php if ($featuredImage) { ?>
                            <?php $featuredImgAlt = $_post->getData('featured_list_img_alt') ?: $_post->getData('featured_img_alt');
                            if (!$featuredImgAlt) {
                                $featuredImgAlt = $_postName;
                            }
                            ?>
                            <span class="_animation-type-zoom bg-img" style="background-image: url(<?= $block->escapeHtml($featuredImage) ?>)"></span>
                            <?php /* <img class="" src="<?= $block->escapeHtml($featuredImage) ?>" alt=""> */ ?>
                        <?php } ?>

                        <?php /*
                            <img src="<?= $imageHelper->init($_post->getFeaturedListImg() ?: $_post->getFeaturedImg())->resize($width, $height); ?>"
                             alt="<?= $block->escapeHtml($featuredImgAlt) ?>" />
                        */?>
                    </a>
                </div>
                <?php } ?>
                <div class="block-info px-3">
                    <h3 class="post-title m-0 mb-2">
                        <a class="post-item-name" title="<?= $_postName ?>" href="<?= $_postUrl ?>">
                            <?= $_postName ?>
                        </a>
                    </h3>
                    <?php if ($featuredImage && $_post->isPublishDateEnabled()) { ?>
                    <div class="block-date">
                        <span class="post-date"><?= $block->escapeHtml($_post->getPublishDate()) ?></span>
                    </div>
                    <?php } ?>
                    <div class="post-description d-none"></div>
                    <div class="read-more d-none"></div>
                </div>
            </div>
            <!-- END post item -->
            <?php } ?>
        </div>
        <!-- END post list -->
    </div>
</div>
<?php } ?>