<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * Please visit Magefan.com for license details (https://magefan.com/end-user-license-agreement).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog sidebar archive template
 *
 * @var $block \Magefan\Blog\Block\Sidebar\Rss
 */
?>
<div class="widget block block-rss" data-bind="scope: 'blog-rss'">
    <div class="block-title">
        <img width="17"
             height="17"
             class="rss-icon"
             src="<?= $block->escapeUrl($block->getViewFileUrl('Magefan_Blog::images/rss-icon.png')) ?>"
             alt="<?= $block->escapeHtml(__('RSS Feed')) ?>" >
        <strong>
            <a target="_blank"
               href="<?= $block->escapeUrl($block->getUrl('blog/rss/feed')) ?>">
                <?= $block->escapeHtml(__('RSS Feed')) ?>
            </a>
        </strong>
    </div>
</div>
