<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * Please visit Magefan.com for license details (https://magefan.com/end-user-license-agreement).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog tag claud sidebar template
 *
 * @var $block \Magefan\Blog\Block\Sidebar\TagClaud
 */
?>
<?php $tags = $block->getTags(); ?>

<?php if (count($tags)) { ?>
    <?php $maxCount = $block->getMaxCount() ?>

<div class="widget block block-tagclaud" data-bind="scope: 'tagclaud'">
    <div class="block-title">
        <strong><?= $block->escapeHtml(__('Tags')) ?></strong>
    </div>

    <div class="tagclaud-hld">
    <?php foreach ($tags as $tag) { ?>
        <?php $title = $block->escapeHtml($tag->getTitle()) ?>
        <span class="<?= $block->escapeHtml($block->getTagClass($tag)) ?>">
            <a href="<?= $block->escapeUrl($tag->getTagUrl()) ?>" title="<?= $block->escapeHtml($title) ?>">
                <?= $block->escapeHtml($title) ?>
            </a>
        </span>
    <?php } ?>
    </div>
</div>
<?php } ?>
