<?php

namespace Magefan\Blog\Block\Adminhtml\Widget;

use Magefan\Blog\Model\ResourceModel\Post\CollectionFactory;

class FeaturedWidgetChooser extends \Magento\Backend\Block\Widget\Grid\Extended
{
    /**
     * @var \Magento\Cms\Model\BlockFactory
     */
    protected $blockFactory;

    /**
     * @var \Magento\Cms\Model\ResourceModel\Block\CollectionFactory
     */
    protected $collectionFactory;

    /**
     * @var \Magento\Framework\View\Helper\SecureHtmlRenderer
     */
     protected $secureHtmlRenderer;

    /**
     * @param \Magento\Backend\Block\Template\Context $context
     * @param CollectionFactory $collectionFactory
     * @param \Magento\Backend\Helper\Data $backendHelper
     * @param array $data
     */
    public function __construct(
        \Magento\Backend\Block\Template\Context $context,
        \Magento\Backend\Helper\Data $backendHelper,
        \Magefan\Blog\Model\ResourceModel\Post\CollectionFactory $collectionFactory,
        \Magento\Cms\Model\BlockFactory $blockFactory,
        \Magento\Framework\View\Helper\SecureHtmlRenderer $secureHtmlRenderer,
        array $data = []
    )
    {
        $this->collectionFactory = $collectionFactory;
        $this->blockFactory = $blockFactory;
        $this->secureHtmlRenderer = $secureHtmlRenderer;
        parent::__construct($context, $backendHelper, $data);
    }

    /**
     * Block construction, prepare grid params
     *
     * @return void
     */
    protected function _construct()
    {
        parent::_construct();
        $this->setDefaultSort('block_identifier');
        $this->setDefaultDir('ASC');
        $this->setUseAjax(true);
        $this->setDefaultFilter(['chooser_is_active' => '1']);
    }

    /**
     * Prepare chooser element HTML
     *
     * @param \Magento\Framework\Data\Form\Element\AbstractElement $element Form Element
     * @return \Magento\Framework\Data\Form\Element\AbstractElement
     */
    public function prepareElementHtml(\Magento\Framework\Data\Form\Element\AbstractElement $element)
    {
        $uniqId = $this->mathRandom->getUniqueHash($element->getId());
        $sourceUrl = $this->getUrl('blog/block_featuredwidget/chooser', ['uniq_id' => $uniqId]);

        $chooser = $this->getLayout()->createBlock(
            \Magento\Widget\Block\Adminhtml\Widget\Chooser::class
        )->setElement(
            $element
        )->setConfig(
            $this->getConfig()
        )->setFieldsetId(
            $this->getFieldsetId()
        )->setSourceUrl(
            $sourceUrl
        )->setUniqId(
            $uniqId
        )->setChooserJsObject(
            $this->getId()
        );

        if ($element->getValue()) {
            $chooser->setLabel($this->escapeHtml((string)$element->getValue()));
        }

        $element->setData('after_element_html', $chooser->toHtml());
        return $element;
    }

    /**
     * Prepare Cms static blocks collection
     *
     * @return \Magento\Backend\Block\Widget\Grid\Extended
     */
    protected function _prepareCollection()
    {
        $this->setCollection($this->collectionFactory->create());
        return parent::_prepareCollection();
    }

    protected function _beforeToHtml()
    {
        $this->secureHtmlRenderer->renderTag(
            'script',
            [],
            'require(["jquery"], function(){
            //<![CDATA[
               console.log(2);
               //]]>
            });'
        );
        return parent::_beforeToHtml(); // TODO: Change the autogenerated stub
    }

    /**
     * Grid Row JS Callback
     *
     * @return string
     */
    public function getRowClickCallback()
    {
        $chooserJsObject = $this->getId();
        $js = '
            function (grid, event) {
                var trElement = Event.findElement(event, "tr");
                var blockId = trElement.down("td").innerHTML.replace(/^\s+|\s+$/g,"");
                var blockTitle = trElement.down("td").next().innerHTML.replace(/^\s+|\s+$/g,"");
                var checkbox = trElement.down("td").down("label").down("input");
                var isChecked = Boolean(checkbox.checked);
                var isRepresent = function(Array,character) {
                                    for (var i = 0; i < Array.length; i++) {
                                        if (Array[i] === character) {
                                            return i;
                                        }
                                    }
                                    return -1;
                                  };
                var currentState = '.
                $chooserJsObject .
                '.getElementValue().replace(/^\s+|\s+$/g,"").split(",");
                var isEmpty = (currentState.length === 1) && (currentState[0] === "");
                if (isChecked === false) {
                    if (!isEmpty) {
                        var index = isRepresent(currentState,blockTitle);
                        if (index === -1) {
                            currentState.push(blockTitle);
                        }
                        blockTitle = currentState.join(",");
                    }
                    checkbox.checked = true;
                }
                if (isChecked === true) {
                 var index = isRepresent(currentState,blockTitle);
                    if (!isEmpty) {
                        var index = isRepresent(currentState,blockTitle);
                        if (index !== -1) {
                            currentState.splice(index, 1)
                        }
                        blockTitle = currentState.join(",");
                    }
                    checkbox.checked = false;
                }
                ' .
            $chooserJsObject .
            '.setElementValue(blockTitle);
                ' .
            $chooserJsObject .
            '.setElementLabel(blockTitle);
            }
        ';
        return $js;
    }

    /**
     * Prepare columns for Cms blocks grid
     *
     * @return \Magento\Backend\Block\Widget\Grid\Extended
     */
    protected function _prepareColumns()
    {
        $this->addColumn(
            'post_id_checkbox',
            [
                'header_css_class' => 'a-center',
                'type' => 'checkbox',
                'name' => 'post_id_checkbox',
                'align' => 'center',
                'index' => 'post_id'
            ]
        );

        $this->addColumn(
            'post_id',
            [
                'header' => __('Post Id'),
                'sortable' => true,
                'index' => 'post_id',
                'header_css_class' => 'col-id',
                'column_css_class' => 'col-id'
            ]
        );
        $this->addColumn(
            'title',
            [
                'header' => __('Title'),
                'index' => 'title'
            ]
        );


//        $this->addColumn(
//            'chooser_identifier',
//            ['header' => __('Identifier'), 'align' => 'left', 'index' => 'identifier']
//        );
//
//        $this->addColumn(
//            'chooser_is_active',
//            [
//                'header' => __('Status'),
//                'index' => 'is_active',
//                'type' => 'options',
//                'options' => [0 => __('Disabled'), 1 => __('Enabled')]
//            ]
//        );

        return parent::_prepareColumns();
    }



    /**
     * Get grid url
     *
     * @return string
     */
    public function getGridUrl()
    {
        return $this->getUrl('blog/block_featuredwidget/chooser', ['_current' => true]);
    }
}