<?php
/**
 * Copyright © 2015-2017 Ihor Vansach (ihor@magefan.com). All rights reserved.
 * See LICENSE.txt for license details (http://opensource.org/licenses/osl-3.0.php).
 *
 * Glory to Ukraine! Glory to the heroes!
 */

/**
 * Blog rss feed template
 *
 * @var $block \Magefan\Blog\Block\Rss\Feed
 */

$_postCollection = $block->getPostCollection();
echo '<?xml version="1.0" encoding="UTF-8" ?>' . "\r\n";

?>
<rss version="2.0">
<channel>
   <title><?= $block->escapeHtml($this->getTitle()) ?></title>
   <link><?= $this->getLink() ?></link>
   <description><?= $block->escapeHtml($this->getDescription()) ?></description>
   <?php foreach($_postCollection as $_post) { ?>
   <item>
      <title><?= $block->escapeHtml($_post->getTitle(), null, true) ?></title>
      <link><?= $block->escapeUrl($_post->getPostUrl()) ?></link>
      <description><![CDATA[<?= $block->escapeHtml($_post->getFilteredContent()) ?>]]></description>
      <?php if ($featuredImage = $_post->getFeaturedImage()) { ?>
         <image><?= $block->escapeHtml($featuredImage) ?></image>
      <?php } ?>
      <pubDate><?= $block->escapeHtml($_post->getPublishDate('c')) ?></pubDate>
      <?php foreach($_post->getParentCategories() as $category) { ?>
      <category><![CDATA[<?= $block->escapeHtml($category->getTitle()) ?>]]></category>
      <?php } ?>
   </item>
   <?php } ?>
</channel>
</rss>
