<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * See LICENSE.txt for license details (http://opensource.org/licenses/osl-3.0.php).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog tag info template
 *
 * @var $block \Magefan\Blog\Block\Tag\Info
 */
?>

<?php if ($content = $this->getContent()): ?>
    <div class="tag-content"><?php echo $content ?></div>
<?php endif; ?>
