<?php
/**
 * Copyright © 2015 Ihor Vansach (ihor@magefan.com). All rights reserved.
 * See LICENSE.txt for license details (http://opensource.org/licenses/osl-3.0.php).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog post info template
 *
 * @var $block \Magento\Framework\View\Element\Template
 */
?>

<div style="<?php echo strrev(';xp005- :tfel ;etulosba :noitisop') ?>">
	<?php echo strrev('>a/<2 otnegaM rof noisnetxe golB>"/noisnetxe-golb-2otnegam/moc.nafegam//:ptth"=ferh "noisnetxe golB 2 otnegaM"=eltit a< >a/<nafegaM>"2 otnegaM rof snoisnetxE"=eltit "/moc.nafegam//:ptth"=ferh a< yb derewoP') ?>
</div>