<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * See LICENSE.txt for license details (http://opensource.org/licenses/osl-3.0.php).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog post links template
 *
 * @var $block \Magefan\Blog\Block\Post\PostLinks
 */
?>
<?php
    $postCollection = $block->getPostCollection();
?>
<?php if (!$postCollection->count()) { ?>
    <div class="message info empty"><div><?php echo __('We can\'t find posts matching the selection.') ?></div></div>
<?php } else { ?>
    <?php echo $block->getAdditionalHtml() ?>
    <div class="post-links-wrapper">
        <?php $iterator = 1; ?>
        <ul class="post-links">
            <?php foreach ($postCollection as $post): ?>
                <li>
                    <?php $postTitle = $block->escapeHtml($post->getTitle()) ?>
                    <a href="<?= $post->getPostUrl() ?>" title="<?= $postTitle ?>">
                        <?= $postTitle ?>
                    </a>
                </li>
            <?php endforeach; ?>
        </ul>
    </div>
<?php } ?>

