<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * Please visit Magefan.com for license details (https://magefan.com/end-user-license-agreement).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog recent posts widget
 *
 * @var $block \Magefan\Blog\Block\Widget\Recent
 */
?>

<?php
    $_postCollection = $block->getPostCollection();
    $count = (int) $_postCollection->count();

    //$count = 3;
    $maxCount = $count;
    if ($maxCount > 4) {
        $maxCount = 4;
    }
?>

<?php if ($count) { ?>
    <!-- Mosaica -->
    <div class="mosaica-4 mb-5 items-count-<?= $maxCount ?> clear">

        <!-- block title -->
        <?php if ($block->getTitle()) { ?>
            <div class="block-title-wrap">
                <h4 class="block-title m-0"><?= $block->escapeHtml($block->getTitle()) ?></h4>
            </div>
        <?php } ?>

        <div class="block-inner">
            <div class="block-content d-flex flex-column flex-md-row row-cols-<?= $maxCount ?>">
            <?php $i = 0; ?>
            <?php foreach ($_postCollection as $_post) { ?>
                <?php
                    $i++;
                    if ($i > $maxCount) {
                        break;
                    }
                    $_postUrl = $block->escapeUrl($_post->getPostUrl());
                    $_postName = $block->escapeHtml($_post->getTitle());
                ?>
                <div class="post-block position-relative">
                    <div class="image-container">
                        <!-- post image -->
                        <a class="image-wrap" href="<?= /*@noEscape*/ $_postUrl ?>" title="<?= /*@noEscape*/ $_postName ?>">
                            <?php $featuredImage = $_post->getFeaturedListImage() ?: $_post->getFeaturedImage(); ?>
                            <?php if ($featuredImage) { ?>
                                <?php
                                $featuredImgAlt = $_post->getData('featured_list_img_alt') ?: $_post->getData('featured_img_alt');
                                if (!$featuredImgAlt) {
                                    $featuredImgAlt = $_postName;
                                }
                                ?>
                                <span  class="animation-type-zoom bg-img" style="background-image: url(<?= $block->escapeHtml($featuredImage) ?>)"></span>
                            <?php } ?>
                        </a>
                    </div>

                    <div class="post-info p-4 mb-0">
                        <!-- post category-->
                        <?php if ($_categoriesCount = $_post->getCategoriesCount()) { ?>
                            <?php foreach ($_post->getParentCategories() as $ct) { ?>
                                <a title="<?= $block->escapeHtml($ct->getTitle()) ?>" href="<?= $block->escapeUrl($ct->getCategoryUrl()) ?>" class="post-category"><?= $block->escapeHtml($ct->getTitle()) ?></a>
                            <?php } ?>
                        <?php } ?>
                        <!-- end post category-->

                        <!-- post title -->
                        <div class="post-title-wrap mb-3">
                            <h3 class="post-title">
                                <a href="<?= /*@noEscape*/ $_postUrl ?>"><?= /*@noEscape*/ $_postName ?></a>
                            </h3>
                        </div>
                        <!-- block data -->
                        <div class="post-data-wrap">
                            <!-- post author -->
                            <?php if ($block->authorEnabled()) { ?>
                                <?php if ($_author = $_post->getAuthor()) { ?>
                                    <span class="post-author">
                                                <?php if ($block->authorPageEnabled()) { ?>
                                                    <a title="<?= $block->escapeHtml($_author->getTitle()) ?>"
                                                       href="<?= $block->escapeUrl($_author->getAuthorUrl()) ?>"><?= $block->escapeHtml($_author->getTitle()) ?>
                                                    </a>
                                                <?php } else { ?>
                                                    <?= $block->escapeHtml($_author->getTitle()) ?>
                                                <?php } ?>
                                                <span>-</span>
                                            </span>
                                <?php } ?>
                            <?php } ?>

                            <!-- post data -->
                            <?php if ($_post->isPublishDateEnabled()) { ?>
                                <span class="post-data"><?= $block->escapeHtml($_post->getPublishDate()) ?></span>
                            <?php } ?>
                        </div>
                    </div>
                </div>
            <?php } ?>
            </div>
        </div>
    </div>
    <!-- END Mosaica -->
<?php } ?>