<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * Please visit Magefan.com for license details (https://magefan.com/end-user-license-agreement).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog recent posts widget
 *
 * @var $block \Magefan\Blog\Block\Widget\Recent
 */
?>

<?php
    $_postCollection = $block->getPostCollection();
    $count = (int) $_postCollection->count();
?>

<?php if ($count) { ?>
<!-- Post Grid Three Column Template 2-1 -->
<div class="template-2-1 mb-5">
        <div class="block-inner">
            <!-- block title -->
            <?php if ($block->getTitle()) { ?>
                <div class="block-title-wrap">
                    <h4 class="block-title m-0"><?= $block->escapeHtml($block->getTitle()) ?></h4>
                </div>
            <?php } ?>

            <!-- block content -->
            <div class="block-content m-0">
                <!-- post grid -->
                <div class="block-post-grid">
                    <?php foreach ($_postCollection as $_post) { ?>
                        <?php
                        $_postUrl = $block->escapeUrl($_post->getPostUrl());
                        $_postName = $block->escapeHtml($_post->getTitle());
                        ?>
                        <!-- post item -->
                        <div class="block-post">
                            <!-- img container -->
                            <div class="image-container">
                                <!-- post image -->
                                <a class="image-wrap _4x3" href="<?= /*@noEscape*/ $_postUrl ?>" title="<?= /*@noEscape*/ $_postName ?>">
                                    <?php $featuredImage = $_post->getFeaturedListImage() ?: $_post->getFeaturedImage(); ?>
                                    <?php if ($featuredImage) { ?>
                                        <?php $featuredImgAlt = $_post->getData('featured_list_img_alt') ?: $_post->getData('featured_img_alt');
                                        if (!$featuredImgAlt) {$featuredImgAlt = $_postName;
                                        }
                                        ?>
                                        <span class="animation-type-zoom bg-img" style="background-image: url(<?= $block->escapeHtml($featuredImage) ?>)"></span>
                                    <?php } ?>
                                </a>
                                <!-- post category-->
                                <?php if ($_categoriesCount = $_post->getCategoriesCount()) { ?>
                                    <span class="post-category m-0">
                                    <?php foreach ($_post->getParentCategories() as $ct) { ?>
                                        <a class="category-name"
                                           href="<?= $block->escapeUrl($ct->getCategoryUrl()) ?>"
                                           title="<?= $block->escapeHtml($ct->getTitle()) ?>">
                                        <?= $block->escapeHtml($ct->getTitle()) ?>
                                    </a>
                                    <?php } ?>
                                </span>
                                <?php } ?>
                                <!-- end post category-->
                            </div>

                            <!-- block info -->
                            <div class="post-info">
                                <!-- post title -->
                                <div class="post-title-wrap mb-1">
                                    <h3 class="post-title m-0">
                                        <a href="<?= /*@noEscape*/ $_postUrl ?>"><?= /*@noEscape*/ $_postName ?></a>
                                    </h3>
                                </div>
                                <!-- post data -->
                                <div class="post-data-wrap mb-3">
                                    <!-- post author -->
                                    <?php if ($block->authorEnabled()) { ?>
                                        <?php if ($_author = $_post->getAuthor()) { ?>
                                            <span class="post-author-name">
                                            <?php if ($block->authorPageEnabled()) { ?>
                                                <a title="<?= $block->escapeHtml($_author->getTitle()) ?>"
                                                   href="<?= $block->escapeUrl($_author->getAuthorUrl()) ?>"><?= $block->escapeHtml($_author->getTitle()) ?>
                                                </a>
                                            <?php } else { ?>
                                                <?= $block->escapeHtml($_author->getTitle()) ?>
                                            <?php } ?>
                                            <span>-</span>
                                        </span>
                                        <?php } ?>
                                    <?php } ?>

                                    <!-- post data -->
                                    <?php if ($_post->isPublishDateEnabled()) { ?>
                                        <span class="post-data"><?= $block->escapeHtml($_post->getPublishDate()) ?></span>
                                    <?php } ?>

                                    <!-- post view -->
                                    <?php if ($block->viewsCountEnabled()) { ?>
                                        <?php if ($viewsCount = $_post->getViewsCount()) { ?>
                                            <span class="post-view float-right d-none d-md-block">
                                                <?= $block->escapeHtml($viewsCount)?>
                                            </span>
                                        <?php } ?>
                                    <?php } ?>
                                </div>
                            </div>
                        </div>
                        <!-- end post item -->
                    <?php } ?>
                </div>
            </div>
        </div>
    </div>
<?php } ?>
