<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$mediaUrl = $objectManager->get('Magento\Store\Model\StoreManagerInterface')
    ->getStore()
    ->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
?>

<!-- Template 2 -->
<div class="template-2 my-5">
    <div class="block-inner">
        <div class="block-title-wrap">
            <h4 class="block-title m-0">Category Name 2</h4>
        </div>
        <div class="block-content d-flex flex-column row-cols-1 flex-md-row row-cols-md-2">
            <!-- block left -->
            <div class="block-left">
                <div class="block-wrap px-md-4">
                    <!-- block post -->
                    <div class="block-post">
                        <!-- img container -->
                        <div class="image-container mb-3">
                            <a href="#" class="image-wrap _3x2">
                                <span class="animation-type-zoom bg-img" style="background-image: url(<?= $mediaUrl ?>wysiwyg/h104-696x464.jpg)"></span>
                                <span class="post-category m-0">Fashion</span>
                            </a>
                        </div>
                        <!-- block info -->
                        <div class="post-info">
                            <div class="post-title-wrap mb-1">
                                <h3 class="post-title m-0">
                                    <a href="#">New Templates For Blog. New Templates For Blog. New Templates For Blog.</a>
                                </h3>
                            </div>
                            <div class="post-date mb-3">
                                        <span class="post-author-name">
                                            <a href="#">Armin Vans</a>
                                            <span>-</span>
                                        </span>
                                <span class="post-date">August 7, 2019</span>
                                <span class="post-view float-right">
                                <a href="#">5</a>
                            </span>
                            </div>
                            <div class="post-description">
                                Description Post. Description Post. Description Post.Description Post.Description Post.Description Post.
                                Description Post.Description Post.Description Post.Description Post.
                            </div>
                        </div>
                    </div>
                    <!-- END block post -->

                    <!-- post list -->
                    <div class="post-list mt-4">
                        <!-- post item -->
                        <div class="post-item d-flex mb-4">
                            <div class="image-container">
                                <a class="image-wrap _4x3" title="Hello world!" href="#">
                                    <span class="bg-img" style="background-image: url(<?= $mediaUrl ?>wysiwyg/02.jpg)"></span>
                                </a>
                            </div>
                            <div class="block-info px-3">
                                <h3 class="block-title m-0 mb-2">
                                    <a class="post-item-name" title="Hello world!" href="#">
                                        Post name. Post name. Post name. Post name. Post name. Post name.
                                    </a>
                                </h3>
                                <div class="block-date">
                                    <span class="post-date">August 7, 2019</span>
                                </div>
                            </div>
                        </div>
                        <!-- END post item -->

                        <!-- post item -->
                        <div class="post-item d-flex mb-4">
                            <div class="image-container">
                                <a class="image-wrap _4x3" title="Hello world!" href="#">
                                    <span class="bg-img" style="background-image: url(<?= $mediaUrl ?>wysiwyg/02.jpg)"></span>
                                </a>
                            </div>
                            <div class="block-info px-3">
                                <h3 class="block-title m-0 mb-2">
                                    <a class="post-item-name" title="Hello world!" href="#">
                                        Post name. Post name. Post name. Post name. Post name. Post name.
                                    </a>
                                </h3>
                                <div class="block-date">
                                    <span class="post-date">August 7, 2019</span>
                                </div>
                            </div>
                        </div>
                        <!-- END post item -->
                    </div>
                    <!-- END post list -->
                </div>
            </div>

            <!-- block right -->
            <div class="block-right">
                <div class="block-wrap px-md-4">
                    <!-- block post -->
                    <div class="block-post">
                        <!-- img container -->
                        <div class="image-container mb-3">
                            <a href="#" class="image-wrap _3x2">
                                <span class="animation-type-zoom bg-img" style="background-image: url(<?= $mediaUrl ?>wysiwyg/h104-696x464.jpg)"></span>
                                <span class="post-category m-0">Fashion</span>
                            </a>
                        </div>
                        <!-- block info -->
                        <div class="post-info">
                            <div class="post-title-wrap mb-1">
                                <h3 class="post-title m-0">
                                    <a href="#">New Templates For Blog. New Templates For Blog. New Templates For Blog.</a>
                                </h3>
                            </div>
                            <div class="post-date mb-3">
                                        <span class="post-author-name">
                                            <a href="#">Armin Vans</a>
                                            <span>-</span>
                                        </span>
                                <span class="post-date">August 7, 2019</span>
                                <span class="post-view float-right">
                                <a href="#">5</a>
                            </span>
                            </div>
                            <div class="post-description">
                                Description Post. Description Post. Description Post.Description Post.Description Post.Description Post.
                                Description Post.Description Post.Description Post.Description Post.
                            </div>
                        </div>
                    </div>
                    <!-- END block post -->

                    <!-- post list -->
                    <div class="post-list mt-4">
                        <!-- post item -->
                        <div class="post-item d-flex mb-4">
                            <div class="image-container">
                                <a class="image-wrap _4x3" title="Hello world!" href="#">
                                    <span class="bg-img" style="background-image: url(<?= $mediaUrl ?>wysiwyg/02.jpg)"></span>
                                </a>
                            </div>
                            <div class="block-info px-3">
                                <h3 class="block-title m-0 mb-2">
                                    <a class="post-item-name" title="Hello world!" href="#">
                                        Post name. Post name. Post name. Post name. Post name. Post name.
                                    </a>
                                </h3>
                                <div class="block-date">
                                    <span class="post-date">August 7, 2019</span>
                                </div>
                            </div>
                        </div>
                        <!-- END post item -->

                        <!-- post item -->
                        <div class="post-item d-flex mb-4">
                            <div class="image-container">
                                <a class="image-wrap _4x3" title="Hello world!" href="#">
                                    <span class="bg-img" style="background-image: url(<?= $mediaUrl ?>wysiwyg/02.jpg)"></span>
                                </a>
                            </div>
                            <div class="block-info px-3">
                                <h3 class="block-title m-0 mb-2">
                                    <a class="post-item-name" title="Hello world!" href="#">
                                        Post name. Post name. Post name. Post name. Post name. Post name.
                                    </a>
                                </h3>
                                <div class="block-date">
                                    <span class="post-date">August 7, 2019</span>
                                </div>
                            </div>
                        </div>
                        <!-- END post item -->
                    </div>
                    <!-- END post list -->
                </div>
            </div>
        </div>
    </div>
</div>
<!-- END Template 2 -->