<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$mediaUrl = $objectManager->get('Magento\Store\Model\StoreManagerInterface')
    ->getStore()
    ->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
?>

<!-- Template 4 -->
<div class="template-4 my-5">
    <div class="block-inner">
        <div class="block-title-wrap">
            <h4 class="block-title m-0">Category Name 4</h4>
        </div>
        <div class="block-content m-0">
            <div class="block-post-grid d-grid">
                <!-- block post -->
                <div class="block-post">
                    <!-- img container -->
                    <div class="image-container">
                        <a href="#" class="image-wrap _3x2">
                            <span class="animation-type-zoom bg-img" style="background-image: url(<?= $mediaUrl ?>wysiwyg/h104-696x464.jpg)"></span>
                            <span class="post-category m-0">Fashion</span>
                        </a>
                    </div>
                    <!-- block info -->
                    <div class="post-info pt-3">
                        <div class="post-title-wrap mb-1">
                            <h3 class="post-title m-0">
                                <a href="#">New Templates For Blog. New Templates For Blog. New Templates For Blog.</a>
                            </h3>
                        </div>
                        <div class="post-date mb-3">
                                        <span class="post-author-name">
                                            <a href="#">Armin Vans</a>
                                            <span>-</span>
                                        </span>
                            <span class="post-date">August 7, 2019</span>
                            <span class="post-view float-right">
                                            <a href="#">5</a>
                                        </span>
                        </div>
                        <div class="post-description d-none">
                            Description Post. Description Post. Description Post.Description Post.Description Post.Description Post.
                            Description Post.Description Post.Description Post.Description Post.
                        </div>
                    </div>
                </div>
                <!-- END block post -->

                <!-- block post -->
                <div class="block-post">
                    <!-- img container -->
                    <div class="image-container">
                        <a href="#" class="image-wrap _3x2">
                            <span class="animation-type-zoom bg-img" style="background-image: url(<?= $mediaUrl ?>wysiwyg/h104-696x464.jpg)"></span>
                            <span class="post-category m-0">Fashion</span>
                        </a>
                    </div>
                    <!-- block info -->
                    <div class="post-info pt-3">
                        <div class="post-title-wrap mb-1">
                            <h3 class="post-title m-0">
                                <a href="#">New Templates For Blog. New Templates For Blog. New Templates For Blog.</a>
                            </h3>
                        </div>
                        <div class="post-date mb-3">
                                        <span class="post-author-name">
                                            <a href="#">Armin Vans</a>
                                            <span>-</span>
                                        </span>
                            <span class="post-date">August 7, 2019</span>
                            <span class="post-view float-right">
                                            <a href="#">5</a>
                                        </span>
                        </div>
                        <div class="post-description d-none">
                            Description Post. Description Post. Description Post.Description Post.Description Post.Description Post.
                            Description Post.Description Post.Description Post.Description Post.
                        </div>
                    </div>
                </div>
                <!-- END block post -->

                <!-- block post -->
                <div class="block-post">
                    <!-- img container -->
                    <div class="image-container">
                        <a href="#" class="image-wrap _3x2">
                            <span class="animation-type-zoom bg-img" style="background-image: url(<?= $mediaUrl ?>wysiwyg/h104-696x464.jpg)"></span>
                            <span class="post-category m-0">Fashion</span>
                        </a>
                    </div>
                    <!-- block info -->
                    <div class="post-info pt-3">
                        <div class="post-title-wrap mb-1">
                            <h3 class="post-title m-0">
                                <a href="#">New Templates For Blog. New Templates For Blog. New Templates For Blog.</a>
                            </h3>
                        </div>
                        <div class="post-date mb-3">
                                        <span class="post-author-name">
                                            <a href="#">Armin Vans</a>
                                            <span>-</span>
                                        </span>
                            <span class="post-date">August 7, 2019</span>
                            <span class="post-view float-right">
                                            <a href="#">5</a>
                                        </span>
                        </div>
                        <div class="post-description d-none">
                            Description Post. Description Post. Description Post.Description Post.Description Post.Description Post.
                            Description Post.Description Post.Description Post.Description Post.
                        </div>
                    </div>
                </div>
                <!-- END block post -->

                <!-- block post -->
                <div class="block-post">
                    <!-- img container -->
                    <div class="image-container">
                        <a href="#" class="image-wrap _3x2">
                            <span class="animation-type-zoom bg-img" style="background-image: url(<?= $mediaUrl ?>wysiwyg/h104-696x464.jpg)"></span>
                            <span class="post-category m-0">Fashion</span>
                        </a>
                    </div>
                    <!-- block info -->
                    <div class="post-info pt-3">
                        <div class="post-title-wrap mb-1">
                            <h3 class="post-title m-0">
                                <a href="#">New Templates For Blog. New Templates For Blog. New Templates For Blog.</a>
                            </h3>
                        </div>
                        <div class="post-date mb-3">
                                        <span class="post-author-name">
                                            <a href="#">Armin Vans</a>
                                            <span>-</span>
                                        </span>
                            <span class="post-date">August 7, 2019</span>
                            <span class="post-view float-right">
                                            <a href="#">5</a>
                                        </span>
                        </div>
                        <div class="post-description d-none">
                            Description Post. Description Post. Description Post.Description Post.Description Post.Description Post.
                            Description Post.Description Post.Description Post.Description Post.
                        </div>
                    </div>
                </div>
                <!-- END block post -->

                <!-- block post -->
                <div class="block-post">
                    <!-- img container -->
                    <div class="image-container">
                        <a href="#" class="image-wrap _3x2">
                            <span class="animation-type-zoom bg-img" style="background-image: url(<?= $mediaUrl ?>wysiwyg/h104-696x464.jpg)"></span>
                            <span class="post-category m-0">Fashion</span>
                        </a>
                    </div>
                    <!-- block info -->
                    <div class="post-info pt-3">
                        <div class="post-title-wrap mb-1">
                            <h3 class="post-title m-0">
                                <a href="#">New Templates For Blog. New Templates For Blog. New Templates For Blog.</a>
                            </h3>
                        </div>
                        <div class="post-date mb-3">
                                        <span class="post-author-name">
                                            <a href="#">Armin Vans</a>
                                            <span>-</span>
                                        </span>
                            <span class="post-date">August 7, 2019</span>
                            <span class="post-view float-right">
                                            <a href="#">5</a>
                                        </span>
                        </div>
                        <div class="post-description d-none">
                            Description Post. Description Post. Description Post.Description Post.Description Post.Description Post.
                            Description Post.Description Post.Description Post.Description Post.
                        </div>
                    </div>
                </div>
                <!-- END block post -->

                <!-- block post -->
                <div class="block-post">
                    <!-- img container -->
                    <div class="image-container">
                        <a href="#" class="image-wrap _3x2">
                            <span class="animation-type-zoom bg-img" style="background-image: url(<?= $mediaUrl ?>wysiwyg/h104-696x464.jpg)"></span>
                            <span class="post-category m-0">Fashion</span>
                        </a>
                    </div>
                    <!-- block info -->
                    <div class="post-info pt-3">
                        <div class="post-title-wrap mb-1">
                            <h3 class="post-title m-0">
                                <a href="#">New Templates For Blog. New Templates For Blog. New Templates For Blog.</a>
                            </h3>
                        </div>
                        <div class="post-date mb-3">
                                        <span class="post-author-name">
                                            <a href="#">Armin Vans</a>
                                            <span>-</span>
                                        </span>
                            <span class="post-date">August 7, 2019</span>
                            <span class="post-view float-right">
                                            <a href="#">5</a>
                                        </span>
                        </div>
                        <div class="post-description d-none">
                            Description Post. Description Post. Description Post.Description Post.Description Post.Description Post.
                            Description Post.Description Post.Description Post.Description Post.
                        </div>
                    </div>
                </div>
                <!-- END block post -->
            </div>

        </div>
    </div>
</div>
<!-- END Template 4 -->