<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$mediaUrl = $objectManager->get('Magento\Store\Model\StoreManagerInterface')
    ->getStore()
    ->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
?>

<!-- One column Post List Template 10 -->
<div class="template-10 my-5">
    <div class="block-inner">
        <div class="block-title-wrap">
            <h4 class="block-title m-0">Template 10</h4>
        </div>
        <div class="block-content">
            <!-- post list -->
            <div class="post-list">
                <!-- post item -->
                <div class="post-item d-flex mb-4">
                    <!-- img container -->
                    <div class="image-container">
                        <a href="#" class="image-wrap _4x3">
                            <span class="animation-type-zoom animation-type-zoom bg-img" style="background-image: url(<?= $mediaUrl ?>wysiwyg/02.jpg)"></span>
                            <span class="post-category m-0">Fashion</span>
                        </a>
                    </div>
                    <!-- block info -->
                    <div class="post-info">
                        <div class="post-title-wrap mb-2">
                            <h3 class="post-title m-0">
                                <a href="#">New Templates For Blog. New Templates For Blog. New Templates For Blog.</a>
                            </h3>
                        </div>
                        <div class="post-date mb-3">
                            <span class="post-author-name">
                                <a href="#">Armin Vans</a>
                                <span>-</span>
                            </span>
                            <span class="post-date">August 7, 2019</span>
                            <span class="post-view float-right d-none d-md-block">
                                <a href="#">5</a>
                            </span>
                        </div>
                        <div class="post-description d-none d-md-block">
                            Description Post. Description Post. Description Post.Description Post.Description Post.Description Post.
                            Description Post.Description Post.Description Post.Description Post.
                            Description Post. Description Post. Description Post.Description Post.Description Post.Description Post.
                            Description Post.Description Post.Description Post.Description Post.
                            Description Post. Description Post. Description Post.Description Post.Description Post.Description Post.
                            Description Post.Description Post.Description Post.Description Post.
                        </div>
                        <div class="read-more d-none">Read More</div>
                    </div>
                </div>
                <!-- end post item -->

                <!-- post item -->
                <div class="post-item d-flex mb-4">
                    <!-- img container -->
                    <div class="image-container">
                        <a href="#" class="image-wrap _4x3">
                            <span class="animation-type-zoom bg-img" style="background-image: url(<?= $mediaUrl ?>wysiwyg/02.jpg)"></span>
                            <span class="post-category m-0">Fashion</span>
                        </a>
                    </div>
                    <!-- block info -->
                    <div class="post-info">
                        <div class="post-title-wrap mb-2">
                            <h3 class="post-title m-0">
                                <a href="#">New Templates For Blog. New Templates For Blog. New Templates For Blog.</a>
                            </h3>
                        </div>
                        <div class="post-date mb-3">
                            <span class="post-author-name">
                                <a href="#">Armin Vans</a>
                                <span>-</span>
                            </span>
                            <span class="post-date">August 7, 2019</span>
                            <span class="post-view float-right d-none d-md-block">
                                <a href="#">5</a>
                            </span>
                        </div>
                        <div class="post-description d-none d-md-block">
                            Description Post. Description Post. Description Post.Description Post.Description Post.Description Post.
                            Description Post.Description Post.Description Post.Description Post.
                        </div>
                    </div>
                </div>
                <!-- end post item -->

                <!-- post item -->
                <div class="post-item d-flex mb-4">
                    <!-- img container -->
                    <div class="image-container">
                        <a href="#" class="image-wrap _4x3">
                            <span class="animation-type-zoom animation-type-zoom bg-img" style="background-image: url(<?= $mediaUrl ?>wysiwyg/02.jpg)"></span>
                            <span class="post-category m-0">Fashion</span>
                        </a>
                    </div>
                    <!-- block info -->
                    <div class="post-info">
                        <div class="post-title-wrap mb-2">
                            <h3 class="post-title m-0">
                                <a href="#">New Templates For Blog. New Templates For Blog. New Templates For Blog.</a>
                            </h3>
                        </div>
                        <div class="post-date mb-3">
                            <span class="post-author-name">
                                <a href="#">Armin Vans</a>
                                <span>-</span>
                            </span>
                            <span class="post-date">August 7, 2019</span>
                            <span class="post-view float-right d-none d-md-block">
                                <a href="#">5</a>
                            </span>
                        </div>
                        <div class="post-description d-none d-md-block">
                            Description Post. Description Post. Description Post.Description Post.Description Post.Description Post.
                            Description Post.Description Post.Description Post.Description Post.
                        </div>
                    </div>
                </div>
                <!-- end post item -->

                <!-- post item -->
                <div class="post-item d-flex mb-4">
                    <!-- img container -->
                    <div class="image-container">
                        <a href="#" class="image-wrap _4x3">
                            <span class="animation-type-zoom animation-type-zoom bg-img" style="background-image: url(<?= $mediaUrl ?>wysiwyg/02.jpg)"></span>
                            <span class="post-category m-0">Fashion</span>
                        </a>
                    </div>
                    <!-- block info -->
                    <div class="post-info">
                        <div class="post-title-wrap mb-2">
                            <h3 class="post-title m-0">
                                <a href="#">New Templates For Blog. New Templates For Blog. New Templates For Blog.</a>
                            </h3>
                        </div>
                        <div class="post-date mb-3">
                            <span class="post-author-name">
                                <a href="#">Armin Vans</a>
                                <span>-</span>
                            </span>
                            <span class="post-date">August 7, 2019</span>
                            <span class="post-view float-right d-none d-md-block">
                                <a href="#">5</a>
                            </span>
                        </div>
                        <div class="post-description d-none d-md-block">
                            Description Post. Description Post. Description Post.Description Post.Description Post.Description Post.
                            Description Post.Description Post.Description Post.Description Post.
                        </div>
                    </div>
                </div>
                <!-- end post item -->

                <!-- post item -->
                <div class="post-item d-flex mb-4">
                    <!-- img container -->
                    <div class="image-container">
                        <a href="#" class="image-wrap _4x3">
                            <span class="animation-type-zoom animation-type-zoom bg-img" style="background-image: url(<?= $mediaUrl ?>wysiwyg/02.jpg)"></span>
                            <span class="post-category m-0">Fashion</span>
                        </a>
                    </div>
                    <!-- block info -->
                    <div class="post-info">
                        <div class="post-title-wrap mb-2">
                            <h3 class="post-title m-0">
                                <a href="#">New Templates For Blog. New Templates For Blog. New Templates For Blog.</a>
                            </h3>
                        </div>
                        <div class="post-date mb-3">
                            <span class="post-author-name">
                                <a href="#">Armin Vans</a>
                                <span>-</span>
                            </span>
                            <span class="post-date">August 7, 2019</span>
                            <span class="post-view float-right d-none d-md-block">
                                <a href="#">5</a>
                            </span>
                        </div>
                        <div class="post-description d-none d-md-block">
                            Description Post. Description Post. Description Post.Description Post.Description Post.Description Post.
                            Description Post.Description Post.Description Post.Description Post.
                        </div>
                    </div>
                </div>
                <!-- end post item -->
            </div>
            <!-- END post list -->
        </div>
    </div>
</div>
<!-- END Template 3 -->