<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * Please visit Magefan.com for license details (https://magefan.com/end-user-license-agreement).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog post media gallery images template
 *
 * @var $block \Magefan\Blog\Block\Post\View\Gallery
 * @var $mfSecureRenderer \Magefan\Community\Api\SecureHtmlRendererInterface
 * @var $mfBreezeThemeDetection \Magefan\Community\Api\BreezeThemeDetectionInterface
 */
?>
<?php
    $post = $block->getPost();
    $galleryImages = $post->getGalleryImages();
    $viewFileUrl = $block->getViewFileUrl("Magefan_Blog::css/jquery.fancybox.min.css");
?>
<?php if (count($galleryImages)) { ?>
    <div class="post-gallery clearfix">
        <?php foreach ($galleryImages as $image) { ?>
            <a class="gallery-image-hld"
               data-fancybox="gallery"
               href="<?= $block->escapeUrl($image) ?>"
               rel="nofollow">
                <img class="gallery-image" src="<?= $block->escapeUrl($image->resize(200, 133)) ?>" alt="" />
            </a>
        <?php } ?>
    </div>
    <?php if ($mfBreezeThemeDetection->execute()) {
        $script = "
            var _deepestScroll = 0;
    
            function initFancyBox(firstCheck) {
                if (!firstCheck && _deepestScroll + 50 > document.documentElement.scrollTop) {
                    return;
                }
    
                _deepestScroll = document.documentElement.scrollTop;
    
                let fancyGallery = document.querySelector('.post-gallery');
                let offset = 150;
                let isFancyGalleryVisible = ((fancyGallery.getBoundingClientRect().top - offset) < window.innerHeight);
    
                if (isFancyGalleryVisible) {
                    document.removeEventListener('scroll', initFancyBox);
    
                    const link = document.createElement('link')
                    link.rel = 'stylesheet';
                    link.type = 'text/css';
                    link.href = 'https://cdn.jsdelivr.net/npm/@fancyapps/ui/dist/fancybox.css';
                    document.head.append(link);
    
                    const script = document.createElement('script')
                    script.src = 'https://cdn.jsdelivr.net/npm/@fancyapps/ui@4.0/dist/fancybox.umd.js';
                    document.head.append(script);
                }
            }
    
            initFancyBox(true);
            document.addEventListener('scroll', initFancyBox);
        ";
    } else {
        $script = "
            require(['jquery', 'domReady!'], function($){
                /* Deferer fancybox css loading */
                $('head').append(
                    $(\"<link rel='stylesheet' href='" . $block->escapeUrl($viewFileUrl) . "' type='text/css' media='screen' />\")
                );
                /* Deferer fancybox js loading */
                require(['jquery', 'Magefan_Blog/js/jquery.fancybox.min'], function(){});
            });
        ";
    } ?>
    <?= /* @noEscape */ $mfSecureRenderer->renderTag('script', [], $script, false) ?>
<?php } ?>


