<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * Please visit Magefan.com for license details (https://magefan.com/end-user-license-agreement).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog related posts template
 *
 * @var $block \Magefan\Blog\Block\Post\View\RelatedPosts
 */
?>

<?php if ($block->displayPosts()) { ?>
    <?php $postCollection = $block->getPostCollection(); ?>
    <?php if (count($postCollection)) { ?>
    <div class="block related">
        <div class="block-title title">
            <strong id="block-relatedposts-heading"><?= $block->escapeHtml(__('Related Posts')) ?></strong>
        </div>
        <div class="block-content">
            <!-- post list -->
            <div class="post-list">
                <?php foreach ($postCollection as $post) { ?>
                    <?php
                        $_postUrl = $block->escapeUrl($post->getPostUrl());
                        $_postName = $block->escapeHtml($post->getTitle());
                    ?>
                    <!-- post item -->
                    <div class="post-item d-flex mb-4">
                        <?php $featuredImage = $post->getFeaturedListImage() ?: $post->getFeaturedImage(); ?>
                        <?php if ($featuredImage) { ?>
                            <div class="image-container">
                                <?php
                                    $featuredImgAlt = $post->getData('featured_list_img_alt') ?: $post->getData('featured_img_alt');
                                    if (!$featuredImgAlt) {
                                        $featuredImgAlt =  $_postName;
                                    }
                                ?>
                                <a class="image-wrap _4x3" title="<?= $_postName ?>" href="<?= $_postUrl ?>">
                                    <?php $featuredImage = $post->getFeaturedListImage() ?: $post->getFeaturedImage(); ?>
                                    <?php if ($featuredImage) { ?>
                                        <?php $featuredImgAlt = $post->getData('featured_list_img_alt') ?: $post->getData('featured_img_alt');
                                        if (!$featuredImgAlt) {
                                            $featuredImgAlt = $_postName;
                                        }
                                        ?>
                                        <span class="animation-type-zoom bg-img" style="background-image: url(<?= $block->escapeHtml($featuredImage) ?>)"></span>
                                    <?php } ?>
                                </a>
                            </div>
                        <?php } ?>
                        <div class="block-info px-3">
                            <h3 class="post-title m-0 mb-2">
                                <a class="post-item-name" title="<?= $_postName ?>" href="<?= $_postUrl ?>">
                                    <?= $_postName ?>
                                </a>
                            </h3>
                        </div>
                    </div>
                    <!-- END post item -->
                <?php } ?>
            </div>
            <!-- END post list -->
        </div>
    </div>
    <?php } ?>
<?php } ?>