<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * Please visit Magefan.com for license details (https://magefan.com/end-user-license-agreement).
 *
 * Glory to Ukraine! Glory to the heroes!
 */

/**
 * @var \Magefan\Blog\Block\ViewCounter $block
 */
?>
<script>
    require(['jquery', 'domReady!'], function($){
        setTimeout(function(){
            $.ajax({
                url:"<?= $block->escapeUrl($block->getUrl('blog/post/counter'));?>",
                type:'POST',
                data: {id: <?= (int)$block->getRequest()->getParam('id'); ?> },
                dataType: 'json',
                success: function(response) { }
            })
        }, 5000);
    });

</script>


