<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * Please visit Magefan.com for license details (https://magefan.com/end-user-license-agreement).
 *
 * Glory to Ukraine! Glory to the heroes!
 */

/**
 * @var \Magefan\Blog\Block\ViewsCount $block
 * @var $mfSecureRenderer \Magefan\Community\Api\SecureHtmlRendererInterface
 */
?>
<?php $script = ''; ?>

<?php
$script .= "
    require(['jquery', 'domReady!'], function($){
        setTimeout(function(){
            $.ajax({
                url: atob( '" . base64_encode($block->getCounterUrl()) . "'),
                type:'POST',
                dataType: 'json',
                success: function(response) { }
            })
        }, 5000);
    });
"; ?>

<?= /* @noEscape */ $mfSecureRenderer->renderTag('script', [], $script, false) ?>
