.pages .action,.pages .item,.pages .items{display:inline-block}
.post-list{margin-top:20px;margin-bottom:20px;list-style:none}
.post-list .post-content .post-read-more{padding-top:10px;float:right}
.blog-category-view .category-content{padding-left:40px}
.post-list .post-header .post-title{max-width:80%;margin:0;padding:10px 0;float:left}
.post-list .post-header .post-title a{text-decoration:none;font-size:22px;color:#636363}
.pages{margin-bottom:25px;text-align:center}
.pages .items{font-size:0;letter-spacing:-1px;line-height:0;white-space:nowrap;list-style:none;font-weight:400;text-align:center;position:relative;z-index:1}
.pages .item{font-size:12px;letter-spacing:normal;line-height:30px;margin:0 12px}
.pages .action{background:#f0f0f0;border:1px solid #ccc;box-shadow:inset 0 1px 0 0 #fff,inset 0 -1px 0 0 rgba(204,204,204,.3);border-radius:3px;padding:0 8px;color:#7d7d7d;text-decoration:none}
.pages .action.next:before,.pages .action.previous:before{font-family:font-icon;font-size:20px;display:inline-block;position:relative;top:2px}
.pages .action.next:before{content:"\e909"}
.pages .action.previous:before{content:"\e908"}
.pages .action>span,.pages .item .label,.pages>.label{display:none}
@media (max-width:490px){.pages-item-next{position:absolute;right:0;top:0;z-index:1}
	.pages-item-previous{left:0;position:absolute;top:0;z-index:1}
	.pages .items{display:block;padding:2px 54px 0}
	.pages .item.pages-item-next{margin-right:0}
	.pages .item.pages-item-previous{margin-left:0}
}
