.post-holder {padding-bottom: 20px;  margin-bottom: 20px; background: #F9F9F9; padding: 20px}
.post-holder:hover {box-shadow: 3px 3px 4px 0 rgba(0, 0, 0, 0.1);position: relative;z-index: 2}
.post-holder .post-header {position:relative}
.post-holder .post-header .post-info {padding: 0 0 10px 0;}
.post-holder .post-header .post-info .item,
.post-holder .post-header .post-info .dash {display: inline-block}
.post-holder .post-header .post-info .label {font-weight: 700}
.post-holder .post-header .post-info .value {font-style: italic}
.post-content .post-description img {margin:0 15px 0 15px;}
.post-content .post-description ul,
.post-content .post-description ol {list-style-position: inside;}
.post-content .post-description .post-ftimg-hld {float: left; margin: 0 15px 0 15px; width: 33%}
.post-content .post-description .post-ftimg-hld img {width:100%; padding:0px; margin:0px;}
@media (max-width: 496px) {
  .post-content .post-description .post-ftimg-hld {width: 100%; margin:0px;}
}
.widget.block:not(:last-child),
.widget:not(:last-child) {margin-bottom: 40px}
.widget .block-title {margin: 0 0 20px;font-style: normal;font-weight: 400;line-height: 1.42857143;font-size: 1.4rem;}
.widget .block-title strong,
.post-view .block .title strong {font-weight:400}
.widget {clear: both;}
.widget.block-recent-posts .block-content .item {padding: 8px 0 0px 0px;}
.widget.block-categories ul {list-style: initial;padding-left:0px;}
.widget.block-categories ul ul {margin-left:20px;}
.widget.block-categories ul,
.widget.block-categories li {margin: 5px 0 5px 9px;padding: 0px}
.widget.block-rss .rss-icon {float: left; width: 23px; padding-right: 10px;}
/* Tag claud sidebar widget */
.widget.block-tagclaud .smallest{font-size: 0.75em}
.widget.block-tagclaud .small{font-size:1em}
.widget.block-tagclaud .medium{font-size:1.25em}
.widget.block-tagclaud .large{font-size:1.5em}
.widget.block-tagclaud .largest{font-size:2em}
/* Archive sidebar widget */
.widget.block-archive .item {display:inline-block; margin:5px 5px 5px 0; font-size:16px;padding:5px;background-color:#F9F9FF;border: 1px solid #bfbfbf;}