.post-view .post-holder .post-header .addthis_toolbox {float: right;}
.post-view .post-bottom {margin-top:30px;}
.post-view .post-nextprev-hld  {margin-bottom: 30px;}
.post-view .post-nextprev-hld .nextprev-link {font-weight: 700;}
.post-view .post-nextprev-hld .prev-link {float:left}
.post-view .post-nextprev-hld .next-link {float:right}
.post-view .block {margin-bottom: 30px;}
.post-view .block .title {margin-bottom: 10px;}
.post-view .block .title strong {line-height: 1.1;font-size: 1.1rem;margin-top: 2rem;margin-bottom: 2rem;}
.post-view .products-related {text-align:center;}