<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * Please visit Magefan.com for license details (https://magefan.com/end-user-license-agreement).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog available for import template
 *
 * @var $block \Magento\Backend\Block\Template
 */
?>

<table class="available-imports">
    <tr>
        <td class="item">
            <table>
                <tr>
                    <td>
                        <div class="itm-hld"
                             onclick="window.location='<?= $block->escapeUrl($block->getUrl('blog/import/wordpress')) ?>'">
                            <img class="img"
                                 src="<?= $block->escapeUrl($block->getViewFileUrl('Magefan_Blog::images/wordpress.png')) ?>" />
                            <br/>
                            <span class="lable">Import from WordPress<br/><br/></span>
                        </div>
                    </td>
                <tr>
            </table>
        </td>
        <td class="item">
            <table>
                <tr>
                    <td>
                        <div class="itm-hld"
                             onclick="window.location='<?= $block->escapeUrl($block->getUrl('blog/import/aw')) ?>'">
                            <img class="img"
                                 src="<?= $block->escapeUrl($block->getViewFileUrl('Magefan_Blog::images/aw_blog.png')) ?>" />
                            <br/>
                            <span class="lable">Import from AheadWorks<br/><br/></span>
                        </div>
                    </td>
                <tr>
            </table>
        </td>
        <td class="item">
            <table>
                <tr>
                    <td>
                        <div class="itm-hld"
                             onclick="window.location='<?= $block->escapeUrl($block->getUrl('blog/import/aw2')) ?>'">
                            <img class="img"
                                 src="<?= $block->escapeUrl($block->getViewFileUrl('Magefan_Blog::images/aw2_blog.png')) ?>" />
                            <br/>
                            <span class="lable">Import from AheadWorks<br/><br/></span>
                        </div>
                    </td>
                <tr>
            </table>
        </td>
        <td class="item">
            <table>
                <tr>
                    <td>
                        <div class="itm-hld"
                             onclick="window.location='<?= $block->escapeUrl($block->getUrl('blog/import/mageplaza1')) ?>'"
                            >
                            <img class="img"
                                 src="<?= $block->escapeUrl($block->getViewFileUrl('Magefan_Blog::images/mageplaza_m1.png')) ?>" />
                            <br/>
                            <span class="lable">Import from Mageplaza<br/><br/></span>
                        </div>
                    </td>
                <tr>
            </table>
        </td>
        <td class="item">
            <table>
                <tr>
                    <td>
                        <div class="itm-hld" onclick="goToMgImport();">
                            <img class="img"
                                 src="<?= $block->escapeUrl($block->getViewFileUrl('Magefan_Blog::images/mageplaza_m2.png')) ?>" />
                            <br/>
                            <span class="lable">Import from Mageplaza<br/><br/></span>
                            <form id="start_mg_import"
                                  action="<?= $block->escapeUrl($block->getUrl('blog/import/run')) ?>"
                                  method="post">
                                <input type="hidden" name="type" value="mageplaza" />
                                <?= $block->getLayout()->getBlock('formkey')->toHtml() ?>
                            </form>
                        </div>
                    </td>
                <tr>
            </table>
        </td>
        <td class="item">
            <table>
                <tr>
                    <td>
                        <div class="itm-hld"
                             onclick="goToMstImport();">
                            <img class="img"
                                 src="<?= $block->escapeUrl($block->getViewFileUrl('Magefan_Blog::images/mirasvit.png')) ?>" />
                            <br/>
                            <span class="lable">Import from Mirasvit<br/><br/></span>
                            <form id="start_mst_import"
                                  action="<?= $block->escapeUrl($block->getUrl('blog/import/run')) ?>"
                                  method="post">
                                <input type="hidden" name="type" value="mirasvit" />
                                <?= $block->getLayout()->getBlock('formkey')->toHtml() ?>
                            </form>
                        </div>
                    </td>
                <tr>
            </table>
        </td>
    <?php if (\Magefan\Community\Model\UrlChecker::showUrl($block->getUrl())) { ?>
    <tr>
        <td class="item">
            <table>
                <tr>
                    <td>
                        <div class="itm-hld"
                             onclick="window.open('https://magefan.com/migrate-blogger-to-magento2?utm_source=m2admin_blog_import&utm_medium=link&utm_campaign=regular')">
                            <img class="img"
                                 src="<?= $block->escapeUrl($block->getViewFileUrl('Magefan_Blog::images/bloger.jpg')) ?>" />
                            <br/>
                            <span class="lable">Import from Blogger.com<br/><br/></span>
                        </div>
                    </td>
                <tr>
            </table>
        </td>
    </td>
        <td class="item">
            <table>
                <tr>
                    <td>
                        <div class="itm-hld"
                             onclick="window.open('https://magefan.com/migrate-drupal-to-magento2?utm_source=m2admin_blog_import&utm_medium=link&utm_campaign=regular')">
                            <img class="img"
                                 src="<?= $block->escapeUrl($block->getViewFileUrl('Magefan_Blog::images/drupal.jpg')) ?>" />
                            <br/>
                            <span class="lable">Import from Drupal<br/><br/></span>
                        </div>
                    </td>
                <tr>
            </table>
        </td>
        <td class="item">
            <table>
                <tr>
                    <td>
                        <div class="itm-hld"
                             onclick="window.open('https://magefan.com/import-xml-csv-to-magento2-blog?utm_source=m2admin_blog_import&utm_medium=link&utm_campaign=regular')">
                            <img class="img"
                                 src="<?= $block->escapeUrl($block->getViewFileUrl('Magefan_Blog::images/csv.jpg')) ?>" />
                            <br/>
                            <span class="lable">Import from CSV/XML File<br/><br/></span>
                        </div>
                    </td>
                <tr>
            </table>
        </td>
        <td class="item">
            <table>
                <tr>
                    <td>
                        <div class="itm-hld" onclick="window.open('https://magefan.com/migrate-joomla-to-magento2?utm_source=m2admin_blog_import&utm_medium=link&utm_campaign=regular')">
                            <img class="img"
                                 src="<?= $block->escapeUrl($block->getViewFileUrl('Magefan_Blog::images/joomla.jpg')) ?>" />
                            <br/>
                            <span class="lable">Import from Joomla<br/><br/></span>
                        </div>
                    </td>
                <tr>
            </table>
        </td>
        <td class="item">
            <table>
                <tr>
                    <td>
                        <div class="itm-hld"
                             onclick="window.open('http://magefan.com/contact?utm_source=m2admin_blog_import&utm_medium=link&utm_campaign=regular')">
                            <h2 class="img more">Need More?<br/><br/>Other CMS or Extension</h2>
                            <span class="lable">Contact Magefan Team<br/><br/></span>
                        </div>
                    </td>
                <tr>
            </table>
        </td>
        <td class="item"></td>
        <td class="item"></td>
    <?php } ?>
    </tr>
</table>
<script type="text/javascript">
    function goToMgImport()
    {
        if (confirm('Are you sure you want to start import Blog? Attention! Do not run this import again.')) {
            document.getElementById('start_mg_import').submit();
        }
    }
    function goToMstImport()
    {
        if (confirm('Are you sure you want to start import Blog? Attention! Do not run this import again.')) {
            document.getElementById('start_mst_import').submit();
        }
    }

</script>