<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * Please visit Magefan.com for license details (https://magefan.com/end-user-license-agreement).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Help template
 *
 * @var $block \Magefan\Blog\Block\Adminhtml\HyvaThemeChecker
 */
?>
<?php if ($items = $block->getWitchModuleIsInstalled()) { ?>
    <div class="messages">
        <div class="message message-notice notice">
            <div data-ui-id="messages-message-notice" class="linv">
                <?= $block->escapeHtml(__('It looks like you are using the Hyva theme, ' .
                    'but the Hyva Magefan Blog extensions for Hyva compatibility are not installed. ' .
                    'Please install these modules for the proper functioning of the blog module on the Hyva theme:')) ?>
                <div style="margin-left: 30px">
                    <br/>
                    <ul>
                        <?php foreach ($items as $name => $url) { ?>
                            <li>
                                <a href="<?= $block->escapeHtml($url) ?>" target="_blank"><?= $block->escapeHtml($name) ?></a>
                            </li>
                        <?php } ?>
                    </ul>
                </div>
            </div>
        </div>
    </div>
<?php } ?>
