<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * See LICENSE.txt for license details (http://opensource.org/licenses/osl-3.0.php).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog available for to get notification
 *
 * @var $block \Magefan\Blog\Block\Adminhtml\System\Config\Form\UpdateInfo
 */
?>
<?php
if ($block->needToUpdate()) {
    ?>
    <div class="messages">
        <div class="message message-notice notice">
            <div data-ui-id="messages-message-error">
               <?php $html = __('Important: It is recommended to update Blog Extension to the version %1 You can update it via
                    composer or download the new versions archive from <a href="https://magefan.com/magento2-blog-extension">Magefan store</a>.
                    Please <a href="https://magefan.com/contact">contact</a> Magefan if you have any questions or need help with an update', $block->getLatestVersion());
               ?>
                <?= $html ?>
            </div>
        </div>
    </div>
<?php } ?>