<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * Please visit Magefan.com for license details (https://magefan.com/end-user-license-agreement).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog post list item template
 *
 * @var $block \Magefan\Blog\Block\Post\PostList\Item
 */
?>
<?php
$_post = $block->getPost();
$_postUrl = $block->escapeUrl($_post->getPostUrl());
$_postName = $block->escapeHtml($_post->getTitle());
?>
<li class="post-holder post-holder-<?= (int)$_post->getId() ?>">
    <div class="post-header">

        <div class="post-title-holder">
            <h2 class="post-title">
                <a class="post-item-link"
                   href="<?= /*@noEscape*/ $_postUrl ?>">
                    <?= /*@noEscape*/ $_postName ?>
                </a>
            </h2>

            <!-- Post Sharing -->
            <div class="post-sharing post-sharing-top old-post-list-item">
                <div class="share-elements">
                    <div class="icon-wrapper icon-facebook">
                        <div class="icon" title="Facebook">
                            <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 32 32" version="1.1"  class="at-icon at-icon-facebook" style="fill: #ffffff;">
                                <title id="at-svg-facebook-1">Facebook</title>
                                <g><path d="M22 5.16c-.406-.054-1.806-.16-3.43-.16-3.4 0-5.733 1.825-5.733 5.17v2.882H9v3.913h3.837V27h4.604V16.965h3.823l.587-3.913h-4.41v-2.5c0-1.123.347-1.903 2.198-1.903H22V5.16z" fill-rule="evenodd"></path></g>
                            </svg>
                        </div>
                    </div>
                    <div class="icon-wrapper icon-twitter">
                        <div class="icon" title="Twitter">
                            <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 32 32" version="1.1" class="at-icon at-icon-twitter" style="fill: #ffffff;">
                                <title id="at-svg-twitter-2">Twitter</title>
                                <g><path d="M27.996 10.116c-.81.36-1.68.602-2.592.71a4.526 4.526 0 0 0 1.984-2.496 9.037 9.037 0 0 1-2.866 1.095 4.513 4.513 0 0 0-7.69 4.116 12.81 12.81 0 0 1-9.3-4.715 4.49 4.49 0 0 0-.612 2.27 4.51 4.51 0 0 0 2.008 3.755 4.495 4.495 0 0 1-2.044-.564v.057a4.515 4.515 0 0 0 3.62 4.425 4.52 4.52 0 0 1-2.04.077 4.517 4.517 0 0 0 4.217 3.134 9.055 9.055 0 0 1-5.604 1.93A9.18 9.18 0 0 1 6 23.85a12.773 12.773 0 0 0 6.918 2.027c8.3 0 12.84-6.876 12.84-12.84 0-.195-.005-.39-.014-.583a9.172 9.172 0 0 0 2.252-2.336" fill-rule="evenodd"></path></g>
                            </svg>
                        </div>
                    </div>
                </div>
            </div>
            <!-- END Post Sharing -->
        </div>

        <?= /*@noEscape*/ $block->getInfoHtml() ?>
    </div>

    <div class="post-content">
        <div class="post-description clearfix">
            <?php $featuredImage = $_post->getFeaturedListImage() ?: $_post->getFeaturedImage(); ?>
            <?php if ($featuredImage) { ?>
                <?php
                $featuredImgAlt = $_post->getData('featured_list_img_alt') ?: $_post->getData('featured_img_alt');
                if (!$featuredImgAlt) {
                    $featuredImgAlt = $_postName;
                }
                ?>
                <div class="post-ftimg-hld">
                    <a href="<?= /*@noEscape*/ $_postUrl ?>"
                       title="<?= /*@noEscape*/ $_postName ?>">
                        <img src="<?= $block->escapeUrl($featuredImage) ?>"
                             alt="<?= $block->escapeHtml($featuredImgAlt) ?>" />
                    </a>
                </div>
            <?php } ?>
            <div class="post-text-hld clearfix">
                <?= /*@noEscape*/ $block->getShorContent() ?>
            </div>
            <a class="post-read-more"
               href="<?= /*@noEscape*/ $_postUrl ?>"
               title="<?= /*@noEscape*/ $_postName ?>">
                <?= $block->escapeHtml(__('Read more &#187;')) ?>
            </a>
        </div>
    </div>
    <div class="post-footer">

    </div>
</li>
